@host = http://localhost:5000

GET {{host}}/TestAuth/public
Accept: application/json

###
POST http://localhost:8080/realms/sisint-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=sisint-auth-service&grant_type=password&username=admin&password=@dm1N&client_secret=ylpwaJVLL0Ya3VeoSHtfPQUhVDbsy2F2

###
GET {{host}}/TestAuth
Authorization: Bearer {{access_token}}
Accept: application/json